### ISSUE TITLE
Protocol buffer compilation error

### ISSUE THREAD

**Issue by vincenzopalazzo** [breez/breez#134]
Hello, I'm working on LNURL-pay integration and I'm compiling the new version of `message.proto` as described here https://github.com/breez/breezmobile/wiki/Overview-for-Developers#define-the-endpoint-in-breez-library-golang

But I'm receiving the following error

```
protoc-gen-go: unable to determine Go import path for "messages.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
```

Any idea on how to solve this issue?

### additional information

➜  breez git:(lnurl-pay) ✗ protoc --version                                             
libprotoc 3.17.0

➜  breez git:(lnurl-pay) ✗ go version     
go version go1.15.8 linux/amd64

**Comment by vincenzopalazzo** [comment]
The following code can be correct solution? 

➜  breez git:(lnurl-pay) ✗ protoc --go-grpc_out=.  data/messages.proto

**Comment by roeierez** [comment]
> protoc-gen-go: unable to determine Go import path for "messages.proto"

I think it is related to the new option added in protoc 3.17 ( I am running 3.15).
Can you try adding this line to the proto file and run the command again?

`option go_package = ".;data";`

**Comment by vincenzopalazzo** [comment]
Hi @roeierez,

>Can you try adding this line to the proto file and run the command again?

I receive the following error 
```

➜  breez git:(lnurl-pay) ✗ protoc option go_package = ".;data";                                   
Missing output directives.

```

Maybe I need to downgrade the version of the compiler to have compatibility with the documentation?

**Comment by vincenzopalazzo** [comment]
Hello @roeierez,

The solution is the following

In the proto file

`option go_package = "/;data";`

The command

`protoc --proto_path=data --go_out=data data/messages.proto`

Thanks for the help
