### ISSUE TITLE
Go Mobile builds xcframeworks now

### ISSUE THREAD

**Issue by NorrinRadd** [breez/breez#137]
GoMobile updated to 1) require that  output has an .xcframework file extension and 2) build all available architectures into iOS target output in the format of an xcframework.

https://github.com/golang/mobile/pull/65

Observed Behavior
===
 ➜ breez git:(c08c06c) ./build-ios.sh                             
gomobile: static framework name "build/ios/bindings.framework" missing .xcframework suffix

Expected Behavior
===
Successful built of the framework

Reproducible 100% of the  time.
I'll update breez/breezmobile to consume this xcframework in the new PR.

**Comment by kingonly** [comment]
Fixed
