### ISSUE TITLE
Git tag new releases & Use github releases for publishing breez.aar in them

### ISSUE THREAD

**Issue by emanuelb** [breez/breez#158]
Related issue in breezmobile is: https://github.com/breez/breezmobile/issues/479

newest git tag in this repo is "0.5.8-openbeta" from "Apr 21, 2019", git tag new releases for breez that are used in breezmobile versions published to mobile stores, also publishing the "breez.aar" file in github releases will make it easier to test for reproducible-builds (testing the .aar by itself and testing the mobile app with using the binary release)

**Comment by kingonly** [comment]
Done
