### ISSUE TITLE
gomobile init not working from README.md guide for building the `breeze.aar` file

### ISSUE THREAD

**Issue by SiddheshKukade** [breez/breez#183]
### I'm getting the below error.
![image](https://user-images.githubusercontent.com/65951872/219609242-ae445570-3bd5-4bbb-9e81-666bbaa0f803.png)

### Please provide some guidance about how to resolve this.

**Comment by erdemyerebasmaz** [comment]
Our instructions got outdated. See changes in: https://github.com/breez/breez/pull/179 and let us know if it resolves your issue.

**Comment by SiddheshKukade** [comment]
@erdemyerebasmaz Thank you !
