### ISSUE TITLE
Unable to reproduce proto compilation

### ISSUE THREAD

**Issue by schjonhaug** [breez/breez#185]
I’m following the instructions in [overview for developers](https://doc.breez.technology/Overview-for-Developers.html):

--- 
[Define the endpoint in Breez Library (golang):](https://doc.breez.technology/Overview-for-Developers.html#define-the-endpoint-in-breez-library-golang)

1. Use protoc version 3.15
1. [Define the protobuf structure in golang](https://github.com/breez/breez/blob/master/data/messages.proto)
1. Compile the proto: protoc --proto_path=data --go_out=. data/messages.proto
1. [Add the endpoint to the binding package](https://github.com/breez/breez/blob/master/bindings/api.go)

---

I’m on macOs Monterey and got protobuf 3.15 installed, but which version of protoc-gen-go are you using? When I compile the protos, I get a very different result that the one currently in the master branch, see https://gist.github.com/schjonhaug/2adc79404db49c8dab03610ca67a2783

**Comment by schjonhaug** [comment]
I’m still stuck on this issue and since [the output](https://gist.github.com/schjonhaug/2adc79404db49c8dab03610ca67a2783) I get using protobuf 3.15 is so different that yours, I suspect that you’re using a different version of protoc-gen-go than me?

After running protoc, I’m unable to build the framework for iOS:

```
./build-ios.sh
gomobile: ios/arm64: go build -tags ios,experimental,signrpc,walletrpc,chainrpc,invoicesrpc,routerrpc,backuprpc,peerrpc,submarineswaprpc,breezbackuprpc -ldflags -s -w -buildmode=c-archive -o /var/folders/yq/44x07gpx1vj8ttprk2dzb_jw0000gn/T/gomobile-work-2952593437/bindings-ios-arm64.a ./gobind failed: exit status 1
# github.com/breez/breez/bindings
/Users/schjonhaug/Developer/breez/original/breez/bindings/rpc.go:76:7: undefined: data.RegisterBreezAPIServer

```

This works without issues if I leave messages.pb.go unaltered like it is on the master branch .

**Comment by roeierez** [comment]
should be fixed now when this is merged: https://github.com/breez/breez/pull/195
