### ISSUE TITLE
 Issue with "gomobile bind" command while building Android app using Breez SDK

### ISSUE THREAD

**Issue by nikhil478** [breez/breez#189]
I am encountering an issue while trying to build an Android app using the Breez SDK. When running the "gomobile bind" command with the following parameters:
-target=android -o build\android\breez.aar -ldflags="-extldflags=-Wl,-soname,libgojni.so" E:\SDKFolder\breez

I get the following error message:
gomobile: E:\SDKFolder\go\bin\gobind.exe -lang=go,java -outdir=C:\Users\NIKHIL~1\AppData\Local\Temp\gomobile-work-479999736 github.com/breez/breez failed: exit status 1 functions and methods must return either zero or one values, and optionally an error too many result values: func (*github.com/breez/breez.App).GetTxSpentURL() (txSpentURL string, isDefault bool, err error)

It seems like the error is related to a function in the Breez SDK that is returning more than one value, which is not allowed. I would appreciate any help or guidance on how to resolve this issue and successfully build the Android app using the Breez [SDK.]
![Screenshot (572)](https://user-images.githubusercontent.com/67046318/222967122-ff5ea6db-4c83-4bfa-a8d6-543f8dc99b43.png)

**Comment by roeierez** [comment]
This is not how we document to build the aar file. See here for instructions how to do it: https://github.com/breez/breez#building-breez-for-android

Let me know how it went.
