### ISSUE TITLE
Simnet can't pay lightning invoice due to LSPD crashing

### ISSUE THREAD

**Issue by PeteClubSeven** [breez/breez#214]
Hi, I wasn't sure whether to create an issue here or in https://github.com/breez/lspd. Basically a change to LSPD has broken the simnet: https://github.com/breez/lspd/blame/70d6afcf85286f831959ed3c18ece246f25d9085/lnd/client.go#L232.

It seems like the issue is an RPC call to LND is failing because it doesn't exist. The call is GetPeerConnected. Here is the log from my dev-lspd container:
```
2023/07/21 03:11:40 LND: client.GetPeerConnected() error: rpc error: code = Unimplemented desc = unknown method GetPeerConnected for service lnrpc.Lightning
2023/07/21 03:11:40 IsConnected(03dbb7667f66335cbb0d46a1e8f80c1cf39a974c5226d56568b96a02f86fb6fa8f) error: LND: client.GetPeerConnected() error: rpc error: code = Unimplemented desc = unknown method GetPeerConnected for service lnrpc.Lightning
panic: interface conversion: interface {} is *interceptor.InterceptResult, not interceptor.InterceptResult

goroutine 45 [running]:
github.com/breez/lspd/interceptor.(*Interceptor).Intercept(0x400008c720, 0x40003e6f40, {0x4000478b00, 0x20, 0x20}, 0x30550c0, 0x1fb, 0x28b)
        /go/lspd/interceptor/intercept.go:286 +0x220
github.com/breez/lspd/lnd.(*LndHtlcInterceptor).intercept.func2()
        /go/lspd/lnd/interceptor.go:139 +0xa0
created by github.com/breez/lspd/lnd.(*LndHtlcInterceptor).intercept
        /go/lspd/lnd/interceptor.go:137 +0x21c
2023/07/21 03:11:40 exit status 2
```

It's pretty simple to replicate this. Start the dev-simnet with a clean temp directory, run the following script:
```bash
#!/bin/bash
pubkey=$(docker exec dev-breez "/lnd/lncli" -network=simnet getinfo | jq --raw-output '.identity_pubkey')
address=$(docker exec dev-alice "/root/go/bin/lncli" --network simnet newaddress np2wkh | jq --raw-output '.address')

docker exec dev-breez "/lnd/lncli" -network=simnet sendcoins $address 1000000000
docker exec dev-btcd /start-btcctl.sh generate 12

docker exec dev-alice "/root/go/bin/lncli" -network=simnet openchannel --node_key $pubkey --local_amt=10000000 --connect=10.5.0.3:9735 --private
docker exec dev-btcd /start-btcctl.sh generate 12
```

Then try to a lightning invoice from your debug breezmobile client with 
```bash
docker exec dev-alice "/root/go/bin/lncli" -network=simnet payinvoice -f --pay_req <payment_request>
```

**Comment by PeteClubSeven** [comment]
For now I reverted back to a previous working commit for the LSPD repository. You can see my changes here: https://github.com/breez/breez/compare/master...PeteClubSeven:breez:bugfix/broken-lspd-simnet-container

**Comment by JssDWt** [comment]
Hey @PeteClubSeven Thanks for the issue.

Could you try whether this PR fixes the issue for you?
https://github.com/breez/breez/pull/217

**Comment by PeteClubSeven** [comment]
Sorry for the lack of response, I've been unavailable but thanks for the fix, I'll check it out 👍

**Comment by PeteClubSeven** [comment]
I finally got round to this and can confirm it works perfectly now, thanks a lot.

**Comment by JssDWt** [comment]
> I finally got round to this and can confirm it works perfectly now, thanks a lot.

Great, thanks for the feedback.
